# Generated by Django 4.2.2 on 2023-07-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_cars_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tovární_značka', models.TextField()),
                ('obchodní_označení', models.TextField()),
                ('druh_vozidla', models.TextField()),
                ('objem_motoru', models.TextField()),
                ('počet_válců', models.TextField()),
                ('kombinovaný_výkon', models.TextField()),
                ('typ_paliva', models.TextField()),
                ('převodovka', models.TextField()),
                ('typ_pohonu', models.TextField()),
                ('cena_skladového_vozu', models.TextField()),
                ('cena_úvěru', models.TextField()),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
