# Generated by Django 4.2.2 on 2023-07-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='cena_skladového_vozu',
            new_name='cena_skladoveho_vozu',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='cena_úvěru',
            new_name='cena_uveru',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='kombinovaný_výkon',
            new_name='kombinovany_vykon',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='obchodní_označení',
            new_name='obchodni_oznaceni',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='počet_válců',
            new_name='pocet_valcu',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='převodovka',
            new_name='prevodovka',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='tovární_značka',
            new_name='tovarni_znacka',
        ),
    ]
