# Generated by Django 4.2.2 on 2023-07-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_cena_skladového_vozu_car_cena_skladoveho_vozu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ImageField(upload_to='main/image/'),
        ),
    ]
